### PR TITLE
Update /plot music command

### PR DESCRIPTION
**Pull request by N0tMyFaultOG**
## Overview

**Fixes https://github.com/IntellectualSites/PlotSquaredSuggestions/issues/57**

## Description
Can be obtained from the suggestion.

## Checklist
- [X] I included all information required in the sections above
- [X] I tested my changes and approved their functionality
- [X] I ensured my changes do not break other parts of the code
- [X] I read and followed the [contribution guidelines](https://github.com/IntellectualSites/PlotSquared/blob/breaking/CONTRIBUTING.md)

### CODE REVIEW

**Comment by Sauilitired** [comment]
This no longer allows plot members to use the command? That doesn't sound ideal.

**Comment by N0tMyFaultOG** [comment]
Whoops

**Comment by Sauilitired** [comment]
This still won't allow plot members to use the command, as they'll fail the owner/admin check further along.

**Comment by Sauilitired** [comment]
This PR breaks logic and will not be merged. It also has unresolved conflicts and appears abandoned.

**Pull request closed without merging**
