### PR TITLE
Chorus Fruit Steal Bug (Bow Shooting Fix)

### LINKED ISSUE #2615: Chorusfruit Steal BUG
# Bug Report Template:

### Server config info (Debug/file paste links):

https://athion.net/ISPaster/paste/view/426f01896400476d979e953f3a6a8843

### Server type:
**select one**

- [x] Spigot / Paper *(CraftBukkit should not be used, re-test with Spigot first!)*
- [] Sponge *- NOTE: NOT ACTIVELY MAINTAINED*
- [] NukkitX *- NOTE: NOT ACTIVELY MAINTAINED*

### Minecraft Version:
**select one**

- [x] Minecraft 1.14.4 ***This is the ONLY actively maintained target for PlotSquared***
- [] Minecraft 1.13.2
- [] Minecraft Java Edition *other versions, please specify*:
- [] Minecraft Bedrock Edition *specify version*:

### Server build info: 

```
Paper version git-Paper-226 (MC: 1.14.4) (Implementing API version 1.14.4-R0.1-SNAPSHOT)
```

### WorldEdit/FAWE versions:

- [] FAWE *version*:
- [x] WorldEdit *version*: 7.0.1;61bc012

### Description of the problem:

Other players can shoot at my chorus plants using a bow and the chorus plant gets dropped. players can destroy chorusplants on my plot with a bow
### How to replicate:

Let player1 claim a plot and plant a chorusplant. player2 (NO ADMIN PERMISSIONS) shoot with a bow at the chorus plant from player 1

### Other plugins being used on the server:

WorldEdit, P2, Multiverse
### Additional relevant comments/remarks:

# AFFIRMATION OF COMPLETION:

- [x] I included all information required in the sections above
- [x] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of PlotSquared
- [x] I made sure the bug/error is not caused by any other plugin
- [] I didn't read but checked everything above.

### PR DESCRIPTION
**Pull request by DevJoey**
## Overview

**Fixes #2615**
https://github.com/IntellectualSites/PlotSquared/issues/2615#issuecomment-562684704
## Description
I have coded a fix for the problem that anyone can shoot choros fruits on other plots.
I have never before created a pull request because that is my first contribution to a OSRC Plugin.
I have only a Pastebin link with the code :( https://hasteb.in/qiyugagu.cs
```java
@EventHandler
	public void onArrowHit(ProjectileHitEvent event) {
		if (event.getEntity().getShooter() instanceof Player) {
			if (event.getHitBlock() != null) {
				if (event.getHitBlock().getType() == Material.CHORUS_FLOWER) {
					Block flower = event.getHitBlock();
					Player shooter = (Player) event.getEntity().getShooter();
					if (getPlugin().getPlotutils().isPlotSquared()) {
						Plot plantplot = getPlugin().getPlotutils().getPlot(flower.getLocation());
						if (plantplot != null) {
							if (!getPlugin().getPlotutils().isOwner(plantplot, shooter)) {
								getPlugin().getFunctionutils().sendNotify(shooter, "ChorusShooting");
								Ageable ageable = (Ageable) flower.getBlockData();
								event.getEntity().remove();
								flower.setType(Material.AIR);
								getPlugin().getServer().getScheduler().runTask(plugin, () -> {
									flower.setType(Material.CHORUS_FLOWER);
									flower.setBlockData(ageable);
								});
							}
						}
					}
				}
			}
		}

	}
````
## Checklist

- [x] I included all information required in the sections above
- [x] I tested my changes and approved their functionality
- [x] I ensured my changes do not break other parts of the code
- [] I read and followed the [contribution guidelines](https://github.com/IntellectualSites/PlotSquared/blob/breaking/CONTRIBUTING.md)

### CODE REVIEW

**Comment by N0tMyFaultOG** [comment]
@DevJoey could you clarify the goal of this pull request please? Elsewise we are just going to close it because it doesn't make much sense to merge the named branches.

**Comment by Sauilitired** [comment]
This is merging a totally different branch into v4.

**Comment by DevJoey** [comment]
Will this Bug ´be fixed in the future?

**Comment by N0tMyFaultOG** [comment]
If someone addresses the is with a proper PR, yes.

**Pull request closed without merging**
