### PR TITLE
Draft: Recalculate light levels on chunk generation

### LINKED ISSUE #3514: Is LightCleaner still necessary?
### Server Implementation

Paper

### Server Version

1.16.5

### Describe the bug

When generating new chunks with a custom template that includes lighting-blocks, the lighting is not updated after the chunk is placed the first time. Instead LightCleaner was advertised in the past. 

The problem is, that LightCleaner goes into an infinite loop of calculating light for unloaded chunks and this is costing a lot of performance. The author of that plugin said, that the problem relies elsewhere and it is not his fault, so I wonder where this problem comes from.

### To Reproduce

1. Use Template with lighting blocks, for example 'Bridge.template'
2. Generate Chunks
3. See no lighting

### Expected behaviour

PlotSquared should handle the lighting itself.

### Screenshots / Videos

_No response_

### Error log (if applicable)

_No response_

### Plot Debugpaste

https://athion.net/ISPaster/paste/view/ca36ed467388451b9ef4e047cf52e247

### PlotSquared Version

PlotSquared version 6.3.0

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by PierreSchwang**
## Overview

Fixes #3514

## Description
Applies light updates to blocks with light values on chunk generation using a populator and WorldEdits World#applySideEffects-method.
Draft, as sometimes that doesn't seem to work and chunk borders sometimes have rough edges.

## Submitter Checklist

- [x] Make sure you are opening from a topic branch (**/feature/fix/docs/ branch** (right side)) and not your main branch.
- [x] Ensure that the pull request title represents the desired changelog entry.
- [ ] I tested my changes and approved their functionality.
- [x] I ensured my changes do not break other parts of the code
- [x] I read and followed the [contribution guidelines](https://github.com/IntellectualSites/.github/blob/main/CONTRIBUTING.md)

### CODE REVIEW

**Comment by dordsor21** [comment]
What's the performance impact of this? Also is setting blocks via the world safe to do during the populate chunk phase, given neighbour-generation-state requirements?

**Comment by PierreSchwang** [comment]
> What's the performance impact of this? Also is setting blocks via the world safe to do during the populate chunk phase, given neighbour-generation-state requirements?

Before caching the light blocks it was quite laggy, but after caching them when setting them and interating over them changes nothing in performance.
I do update the light levels on population, therefor after the chunk generation itself. It does work as I stated, but sometimes chunk edges or blocks won't update properly

**Comment by dordsor21** [comment]
A reasonable extension to this would be setting NBT data as well (https://github.com/IntellectualSites/PlotSquared/issues/3579)

**Comment by SirYwell** [comment]
At this point, it might make sense to use the new worldgen api (and fallback to the "broken" behavior on older versions)

**Comment by PierreSchwang** [comment]
Is this now superseded / implemented by https://github.com/IntellectualSites/PlotSquared/pull/3659 and can be closed?

**Pull request closed without merging**
