### PR TITLE
Make plugin compatible with DeluxeChat

### PR DESCRIPTION
**Pull request by aaomidi**

### CODE REVIEW

**Comment by Sauilitired** [comment]
I don't see why not.

**Comment by aaomidi** [comment]
Thank you!

Can you please make your buildserver build this? :)

**Comment by Sauilitired** [comment]
@aaomidi Someone else will have to do that, it's not an official buildserver (ours went down due to lack of funding, poor developers = poor infrastructure)

**Comment by aaomidi** [comment]
@Sauilitired That sucks man :( Donation link please?

**Comment by Sauilitired** [comment]
@aaomidi http://www.donation-tracker.com/u/i-s Every single penny helps at this point

**Comment by aaomidi** [comment]
Thanks :) Done.

**Comment by Sauilitired** [comment]
@aaomidi Thanks :) This is really appreciated.

**Pull request merged**
