### PR TITLE
Features/v5/event entity categories

### PR DESCRIPTION
**Pull request by Sauilitired**
This PR aims to clean up the entity handling code, and to further remove platform (and version!) specific code from the event handling. 

This uses the new entity category system that @SirYwell and I pushed to features/v5/internal-updates. 

Here is a summary of what caps and flags use what categories (this should be added to the wiki, as people have been terribly confused about this in the past):

**Edit:** Removed `minecraft:` prefixes. 
The entity lists can be retrieved in-game by using `/plot debug entitytypes`

Mob Caps
- Misc: PROJECTILE, OTHER, HANGING
- Animal: ANIMAL, VILLAGER, TAMEABLE
- Mob: HOSTILE
- Vehicle: VEHICLE
- all other entities count to the global cap (there are none though)

Flags:
- hostile-interact: HOSTILE
- animal-interact: ANIMAL
- tamed-interact: TAMEABLE
- vehicle-use: VEHICLE
- player-interact: PLAYER
- villager-interact: VILLAGER
- misc-interact: HANGING, OTHER
- misc-break: Just armour stands
- hostile-attack: HOSTILE
- hanging-break: HANGING
- tamed-attack: TAMEABLE
- animal-attack: ANIMAL

These are the categories:
- plotsquared:animal: cod donkey squid skeleton_horse mule trader_llama parrot zombie_horse cow horse bee polar_bear pufferfish cat bat salmon fox pig llama iron_golem turtle tropical_fish sheep snow_golem mooshroom ocelot dolphin chicken wolf panda rabbit 

- plotsquared:projectile: ender_pearl dragon_fireball fireball wither_skull llama_spit fishing_bobber experience_bottle egg arrow small_fireball 
snowball spectral_arrow shulker_bullet potion trident 

- plotsquared:tameable: cat trader_llama parrot zombie_horse donkey wolf llama horse skeleton_horse mule 

- plotsquared:hanging: item_frame leash_knot painting 

- plotsquared:vehicle: spawner_minecart donkey pig llama furnace_minecart skeleton_horse mule hopper_minecart trader_llama zombie_horse tnt_minecart boat chest_minecart horse command_block_minecart minecart 

- plotsquared:other: dragon_fireball tnt experience_orb lightning_bolt fireball wither_skull area_effect_cloud evoker_fangs eye_of_ender armor_stand small_fireball firework_rocket falling_block item 

- plotsquared:player: player 

- plotsquared:hostile: blaze pillager skeleton giant elder_guardian zombie_pigman end_crystal ravager ghast guardian vindicator magma_cube spider creeper wither evoker slime illusioner phantom witch wither_skeleton husk ender_dragon cave_spider stray enderman silverfish endermite vex zombie drowned zombie_villager, shulker

- plotsquared:villager: villager wandering_trader

### CODE REVIEW

**Comment by RedstoneFuture** [comment]
I like the idea of a better organization this flags! :)

But I have questions / I see problems:

1. Currently, we have this flags too:

> device-interact
> vehicle-break
> vehicle-place
> hanging-place
> misc-place

What will happen with this?

2. In the one site we define a flag "misc-interact" for HANGING + OTHER, and then we define a "negative" flag named "misc-break" only for armour_stands?

3. So far we have a hostile-cap and a mob-cap.
The hostile-cap include the HOSTILE.
And the mob-cap include HOSTILE + ANIMAL, VILLAGER, TAMEABLE, because animals and monsters / hostile are mobs.

4. Why the interact-flag of vehicle is called "vehicle-use" and not "vehicle-interact" like the other flags?

5. Based on the [minecraft-wiki](https://minecraft.gamepedia.com/Mob) shulkers are a hostile mob.


----------


It's only my opinion. I'm not a bukkit developer with all the work behind it. I'm game-designer and server-owner and my community like plotsquared with the amount of different flags. Maybe with logic names and for all different problems. So I will present a good structure in my opinion and maybe you can inspire you:


### 1. MOBS:

**categorie: "mob" for HOSTILE, ANIMAL,VILLAGER**
- **mob-cap**

**categorie: "hostile" for HOSTILE**
- hostile-interact
- hostile-attack
- **hostile-cap**

**categorie: "animal" for ANIMAL**
- animal-interact
- animal-attack
- **animal-cap**

**categorie: "tamed" for TAMEABLE**
- tamed-interact
- tamed-attack
- **maybe tamed-cap**

**categorie: "player" for PLAYER**
- player-interact
- (pvp)

**categorie: "villager" for VILLAGER**
- villager-interact


### 2. OBJECTS:

**categorie: "hanging" for HANGING**
- hanging-interact
- hanging-place
- hanging-break
- **hanging-cap**

**categorie: "misc" for PROJECTILE, OTHER**
- misc-interact
- misc-place
- misc-break
- **misc-cap**

**categorie: "vehicle" for VEHICLE**
- vehicle-interact
- vehicle-place
- vehicle-break
- **vehicle-cap**

(With or without the vehicle-mobs ... lore and boats are enough I think.)


**categorie: "device" for DEVICE**
- device-interact

(= passive interaction like tripwire, pressure_plate and others ...
https://hub.spigotmc.org/javadocs/spigot/org/bukkit/event/block/Action.html)

**Comment by Sauilitired** [comment]
@RedstoneFuture 
No flags are removed, some of them are just re-done a little. `device-interact` is related to block, not entities, so it is not affected. The other flags rely on bukkit entity interfaces, so they're not affected. Only the ones mentioned in my list have been altered in the pull request. I hope that answers your first question.

> In the one site we define a flag "misc-interact" for HANGING + OTHER, and then we define a "negative" flag named "misc-break" only for armour_stands?

This is indeed rather odd, but was the functionality beforehand as well, and I didn't want to alter it, in case it broke anything. Might be worth changing now though. 

> So far we have a hostile-cap and a mob-cap.
The hostile-cap include the HOSTILE.
And the mob-cap include HOSTILE + ANIMAL, VILLAGER, TAMEABLE, because animals and monsters / hostile are mobs.

The ones listed are the ones we already have. There is a "total" mob cap, then there's a hostile one, and one for non-hostile animals, and one for non-hostile, non-animals. It's a bit confusing, but I think it can be explained very well. 

The biggest problem we're facing is that we cannot change flags, as that would break backwards compatibility, and we need old flags to convert properly. I think it would be a good idea to look towards replacing the interaction and mob-cap flags in the future, maybe for version 6? We would need to find a way to replace old values without breaking any server setups, which is always a challenge. 

> Why the interact-flag of vehicle is called "vehicle-use" and not "vehicle-interact" like the other flags?

I don't know, I don't like it, but we cannot change it now :/

> Based on the minecraft-wiki shulkers are a hostile mob.

Indeed. This is a limitation of the current system, we add all golem types (snowman, iron golem and shulker) to the animals because we wanted the golem type in there, but it might be worth adding these entities separately.

**Comment by Sauilitired** [comment]
Right, I've looked into it. 

So, `misc-interact` mainly handles other objects (although, most notably, armor stands) and hanging objects. There's already a `hanging-break` flag that covers hanging, so `misc-break` shouldn't deal with what. That leaves the "others", but only the armour stand actually needs to be protected out of all those blocks.

**Comment by Sauilitired** [comment]
Some changes have been made:
- Entity counting code now uses the new categories, and we stopped relying on magic numbers internally.
- As there was no way to see the actual cap numbers, I added `/plot caps`.

**Pull request merged**
