### PR TITLE
Test removal of our repository

### PR DESCRIPTION
**Pull request by NotMyFault**
Spinning up a clean test environment to test the preparation removing our repository.

### CODE REVIEW

**Comment by NotMyFault** [comment]
Now we've got only Hyperverse left @Citymonstret. Do we want to temporarily drop it until @md5sha256 starts releasing from the `unbadify` branch? That's the ones that appears to be worked on rn.

**Comment by NotMyFault** [comment]
@Citymonstret When do you plan to cancel the box? I would preferably like to take care of this PR before day x happens.

**Comment by Citymonstret** [comment]
> @Citymonstret When do you plan to cancel the box? I would preferably like to take care of this PR before day x happens.

I mean... as soon as possible? It expires the 24th every month (and renews at the same time)

**Pull request closed without merging**
