### PR TITLE
Replace legacy color codes in flag examples

### PR DESCRIPTION
**Pull request by SirYwell**
## Description

Replaces two usages of legacy color codes in flag value examples.

## Submitter Checklist

- [x] Make sure you are opening from a topic branch (**/feature/fix/docs/ branch** (right side)) and not your main branch.
- [x] Ensure that the pull request title represents the desired changelog entry.
- [x] I tested my changes and approved their functionality.
- [x] I ensured my changes do not break other parts of the code
- [x] I read and followed the [contribution guidelines](https://github.com/IntellectualSites/.github/blob/main/CONTRIBUTING.md)

### CODE REVIEW

**Review by dordsor21 — APPROVED** [review]

**Comment by SirYwell** [comment]
> Minimessage colors are not escaped in the flag description box

I guess templates are currently resolved too by minimessage, I'm wondering if that's still the case in the latest version. If not, we can probably ignore it for now...

**Comment by NotMyFault** [comment]
Next week would be a release week, I'm gonna give it a try later this week and if I don't find something new or there is no more negative feedback, we can pull it by end of the weekend I guess.

**Comment by SirYwell** [comment]
This is indeed fixed in the MM version used in v7. Should we still merge it into v6 or retarget it instead?

**Comment by NotMyFault** [comment]
> This is indeed fixed in the MM version used in v7. Should we still merge it into v6 or retarget it instead?

-0.9 from me, we got it covered in v7, which is fine to me.

**Comment by SirYwell** [comment]
Retargeted and rebased (we'll just ignore the misleading branch name)

**Review by NotMyFault — APPROVED** [review]

**Review by dordsor21 — APPROVED** [review]

**Comment by NotMyFault** [comment]
Thanks for your contribution! We will merge your PR within the next ~24 hours, as outlined in our [PR review process](https://github.com/IntellectualSites/IntellectualSites/blob/main/docs/pull-requests/pull-request-review.adoc#step-3-marking-for-merge).

**Review by Citymonstret — APPROVED** [review]

**Pull request merged**
