### PR TITLE
Fixes #3344, Wrong iterator algorithm in PlotRangeIterator

### LINKED ISSUE #3344: PlotRangeGenerator iterating wrong
### Server Implementation

Paper

### Server Version

1.16.5

### Describe the bug

The bug occurs, if a merged plot is pretty far away from center on the Plot.Y- Axis.
Then the iterator sets this.y to 0 instead of the starting value, which causes the main thread to crash.

### To Reproduce

Start a Server with the latest PlotSquared version installed.
Go to e.g 0,25000 on the plot grid.
merge 2 times on the y axis, and then n times on the x axis, the getRegions() method iterates on n * 25k plots. 
Server crashes because the main-thread pauses for too long.

### Expected behaviour

it should only iterate on the plots inside the start-end fields.

### Screenshots / Videos

_No response_

### Error log (if applicable)

_No response_

### Plot Debugpaste

- fix is coming by myself.

### PlotSquared Version

latest

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by buepas**
## Overview
Yeah dunno, its a very small change and I don't know, the issue says everything...

## Description
This PR Fixes #3344 
## Checklist
- [] Make sure you are opening from a topic branch (**/feature/fix/docs/ branch** (right side)) and not your main branch.
- [] Ensure that the pull request title represents the desired changelog entry.
- [X] I tested my changes and approved their functionality.
- [X] I ensured my changes do not break other parts of the code
- [] I read and followed the [contribution guidelines](https://github.com/IntellectualSites/.github/blob/main/CONTRIBUTING.md)

### CODE REVIEW

**Comment by buepas** [comment]
also sorry if I didn't meet the standards. If you really want me to fit them for this one-liner, I can surely do that!

**Comment by SirYwell** [comment]
Looks good. Could you add a test case in `com.plotsquared.core.plot.PlotRangeIteratorTest` to avoid regressions here? That would be very nice.

**Review by NotMyFault — APPROVED** [review]
Looks good, thanks for the contribution!

**Comment by buepas** [comment]
> Looks good. Could you add a test case in `com.plotsquared.core.plot.PlotRangeIteratorTest` to avoid regressions here? That would be very nice.

Sure! When I come home I will do that

**Comment by buepas** [comment]
About the unit-tests:

It looks like that junit was upgraded to junit 5, but the imports haven't been updated?

Should this be handled in a different PR?

**Comment by NotMyFault** [comment]
Some tests are using JUnit 4, newer ones are using JUnit 5. Targeting the newer one is preferable. But no, you can append it to this PR.

**Review by SirYwell — APPROVED** [review]
Thank you very much!

**Pull request merged**
