### PR TITLE
Hot-fix for https://github.com/IntellectualSites/PlotSquared/issues/3179

### PR DESCRIPTION
**Pull request by Aurelien30000**
Authored by @SirYwell ty!

## Overview

**Fixes https://github.com/IntellectualSites/PlotSquared/issues/3179**

## Checklist

- [x] I included all information required in the sections above
- [x] I tested my changes and approved their functionality
- [x] I ensured my changes do not break other parts of the code
- [x] I read and followed the [contribution guidelines](https://github.com/IntellectualSites/PlotSquared/blob/v6/CONTRIBUTING.md)

### CODE REVIEW

**Review by Citymonstret — APPROVED** [review]

**Review by SirYwell — APPROVED** [review]

**Review by NotMyFault — CHANGES_REQUESTED** [review]
Please use some sane IDE over GitHub to commit changes...

**Comment by Aurelien30000** [comment]
Damn, is that a problem?

**Comment by NotMyFault** [comment]
I mean, doing so would've avoided the current compilation blocker at all.

**Comment by dordsor21** [comment]
Richt, right 🙃

**Comment by Aurelien30000** [comment]
Ok, I'm really sorry, I'll recreate it properly.

**Pull request closed without merging**
