### PR TITLE
fix: mob cap counting for each connected plot individually

### LINKED ISSUE #3050: Mob cap on merged plots is not working
### Server Implementation

Paper

### Server Version

1.16.5

### Describe the bug

The mob cap on merged plots does not work. It looks like it handels the mob cap on eac sub plot individuatly and at the same time on the whole plot. 
Setting the mob cap lets you place more than the allowed mobs on the plot. Sometimes you can't and have to move to another sub plot and you can place one more.
The `/p caps` command apperently works for the sub plots, as it clearly doesn't show all mobs and changes if you move to a different sub plot.
This behavier happens to all caps other than the misc-cap.

### To Reproduce

1. Claim a plot and merge more plots to it
2. Set mob-cap to something
3. Place some mobs on the plot. Try to fly arround while placing them
4. check `/p caps` and see how it behaves on different subplots

### Expected behaviour

caps are either the whole plot or each sub plot, but no a mixture of both.

### Screenshots / Videos

-

### Error log (if applicable)

-

### Plot Debugpaste

https://athion.net/ISPaster/paste/view/71147f64df514e6e98d8c595927a36f3

### PlotSquared Version

PlotSquared-5.13.11-Premium

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by Xaver106**
## Overview

Fixes #3050

## Description

handles entity counting with the base plot, eliminating inaccurate mob caps on merged plots and resulting in more entities on a plot than allowed by the mob cap.

## Submitter Checklist

- [X] Make sure you are opening from a topic branch (**/feature/fix/docs/ branch** (right side)) and not your main branch.
- [X] Ensure that the pull request title represents the desired changelog entry.
- [X] New public fields and methods are annotated with `@since TODO`.
- [X] I read and followed the [contribution guidelines](https://github.com/IntellectualSites/.github/blob/main/CONTRIBUTING.md).

### CODE REVIEW

**Comment by dordsor21** [comment]
I think that it would be ideal to set this as a config option, and then have the mob count max set based on the number of plots if enabled/disabled/whatever.

**Comment by Xaver106** [comment]
I agree, but this fixes inconsistencies. Counting all entities on a plot counts on all connected plots, not just the plot the entity spawns. This would result in the entity cap working on a per plot bases until after the plot meta _expires_ then it recounts, counting entities on all connected plots, no longer allowing a per plot cap.
The overall result was inconsistent enforcement of caps.

**Comment by NotMyFault** [comment]
> I think that it would be ideal to set this as a config option, and then have the mob count max set based on the number of plots if enabled/disabled/whatever.

Increasing the *-count on a per-plot basis for merged plots sounds like a different feature and is out of the scope of this PR.

**Review by NotMyFault — APPROVED** [review]

**Comment by NotMyFault** [comment]
Thanks for your contribution! We will merge your PR within the next ~24 hours, as outlined in our [PR review process](https://github.com/IntellectualSites/IntellectualSites/blob/main/docs/pull-requests/pull-request-review.adoc#step-3-marking-for-merge).

**Pull request merged**
