### PR TITLE
Updated and corrected French translation

### PR DESCRIPTION
**Pull request by Aurelien30000**
## Overview

_Not related with an issue._

## Description
Old translation has been reviewed and new v5 flags' translations has been added.
Some mistakes could sadly remain, despite a huge attention, I will fix them if needed ;)

Enjoy and thanks !

## Checklist

- [x] I included all information required in the sections above
- [x] I tested my changes and approved their functionality
- [x] I ensured my changes do not break other parts of the code
- [x] I read and followed the [contribution guidelines](https://github.com/IntellectualSites/PlotSquared/blob/v5/CONTRIBUTING.md)

### CODE REVIEW

**Comment by Aurelien30000** [comment]
Two lines were not translated because I don't understand correctly what they mean, I added a comment `# Not translated, I don't understand :/`. If possible, explain me better and I will be able to translate them :D

**Comment by dordsor21** [comment]
Thank you for your contribution!

The "forcefield" is like a shield around players so that other players cannot get too close.

I also think you might have accidentally deleted some config entries? Or are those entries that are no longer used?

**Comment by Aurelien30000** [comment]
I started my translation from the default generated file of PS v5, so I think they are unused, also no lack of translations during my tests.

Thanks for the tip, I need also explanations on line 319 please, I will add both translations later, PR will be ready in a few hours.

**Comment by N0tMyFaultOG** [comment]
> I started my translation from the default generated file of PS v5, so I think they are unused, also no lack of translations during my tests.
> 
> Thanks for the tip, I need also explanations on line 319 please, I will add both translations later, PR will be ready in a few hours.

`PLOT_LIST_FOOTER` could be removed. I cannot find its usage outside of captions.

**Comment by Aurelien30000** [comment]
> > I started my translation from the default generated file of PS v5, so I think they are unused, also no lack of translations during my tests.
> > Thanks for the tip, I need also explanations on line 319 please, I will add both translations later, PR will be ready in a few hours.
> 
> `PLOT_LIST_FOOTER` could be removed. I cannot find its usage outside of captions.
> Edit: Check my pr

Which PR should I check ? 🤔  (I didn't find anything about)

**Comment by N0tMyFaultOG** [comment]
> Which PR should I check ? 🤔 (I didn't find anything about)

The one I forgot to open lol

**Comment by Aurelien30000** [comment]
Modifications done !

**Pull request merged**
