### PR TITLE
Remove members when buying a plot + Fix /plot delete issue #2351

### PR DESCRIPTION
**Pull request by UnioDex**
Fixes that: https://github.com/IntellectualSites/PlotSquaredSuggestions/issues/48

### CODE REVIEW

**Comment by MattBDev** [comment]
The database needs to be called to properly remove all these players.

**Comment by UnioDex** [comment]
> The database needs to be called to properly remove all these players.

Changed the way to remove players. I think it will work now.

**Comment by UnioDex** [comment]
I added some commits to fix #2351

**Comment by MattBDev** [comment]
Squash the first two commits into one and do the same for the two that follow. Then I'll merge it.

**Comment by UnioDex** [comment]
Here you go:
https://github.com/IntellectualSites/PlotSquared/pull/2353
 @MattBDev

**Pull request closed without merging**
