### PR TITLE
Fix emptying buckets in plot border

### PR DESCRIPTION
**Pull request by traksag**
## Overview

You can currently place water in the plot border as follows: place a waterloggable block on the edge of your plot, waterlog it, click on the side of the block connecting to the plot border with a water bucket. The water will be placed inside the plot border.

Similarly, you can also place lava in plot borders. You don't even need to waterlog the block (although the block does need to be waterloggable).

## Description

In the `PlayerBucketEmptyEvent` listener, fix the code that determines where the fluid is going to be placed:
- If the waterloggable block is waterlogged, the water is going to be placed on the side.
- If the bucket contains lava, the lava is going to be placed on the side.

A month after Bukkit updated to 1.14.4, the `PlayerBucketEmptyEvent` got the API method `getBlock()` that tells you where the fluid is going to be placed. Using that API method would make PlotSquared more robust to future Minecraft changes. However, I believe v6 is supposed to support 1.13, so I opted against using that API method.

## Checklist

- [x] I included all information required in the sections above
- [x] I tested my changes and approved their functionality
- [x] I ensured my changes do not break other parts of the code
- [x] I read and followed the [contribution guidelines](https://github.com/IntellectualSites/PlotSquared/blob/v6/CONTRIBUTING.md)

### CODE REVIEW

**Comment by NotMyFault** [comment]
Unless I [tested it](https://streamable.com/w0f6ko) improperly, this doesn't do anything but creates more issues?

**Comment by traksag** [comment]
The v6 branch has the same behaviour as in your video. Here's a video of the two issues this pull requests aims to resolve (placing water and lava inside the plot border):

https://user-images.githubusercontent.com/58818927/127784314-31ad87ea-c26c-406b-8cac-af082afb48a8.mov

**Comment by NotMyFault** [comment]
Oic, thanks for the clarification. Looks like I reproduced the description improperly or discovered another weird edge case 👀

**Review by NotMyFault — APPROVED** [review]
LGTM, the comment is valid, but we retain 1.13 support for now. Welp, somewhat of. Nobody really uses that version anyway anymore.

**Review by SirYwell — COMMENTED** [review]
Could you add a comment in the code that `getBlock()` could be used on newer versions? That could be helpful in future.

**Review by SirYwell — APPROVED** [review]
Thanks!

**Pull request merged**
