### PR TITLE
Clean the project [WIP]

### PR DESCRIPTION
**Pull request by sgdc3**
I still need to move the sponge implementation to a separate maven module.

### CODE REVIEW

**Comment by Sauilitired** [comment]
@sgdc3 Commits named "Whoops" are always reassuring xD

**Comment by sgdc3** [comment]
@Sauilitired i know, but take a look, i've fixed some huge issues with the pom file.

**Comment by sgdc3** [comment]
Compilation log: http://ci.xephi.fr/job/PlotSquared-sgdc3Edit/4/console

**Comment by Sauilitired** [comment]
@sgdc3 Do you feel that this is ready, or are you still planning to add onto it?

**Comment by sgdc3** [comment]
My plan is to split the project into 3 modules: bukkit, sponge and api.

**Comment by sgdc3** [comment]
But if you want to merge now you can, but consider that atm i moved the entire sponge package outside the java src directory.

**Comment by Sauilitired** [comment]
@sgdc3 I like what you're doing with maven. I am merely just a beginner, and there is a lot for me to learn. Looking forward to see where this is going :)

**Comment by sgdc3** [comment]
Ok, i decided to don't split the project due to the amount of work required xD 
I'm now trying to fix the sponge compiling process.

**Comment by sgdc3** [comment]
Ok i kept sponge into the sources but i excluded it from compilation. 
It should be ready to be merged ;) @Sauilitired

**Pull request merged**
