### PR TITLE
Add events for plot buying

### PR DESCRIPTION
**Pull request by PierreSchwang**
## Overview
Required for https://github.com/IntellectualSites/HoloPlots/issues/171

Usage (and my tests):
```java
@Subscribe
    public void onPlayerBuyPlot(PlayerBuyPlotEvent event) {
        // Cancel / Disallow plot buy
        event.setEventResult(Result.DENY);
        
        // Modify price
        event.setPrice(event.price() * 1.337);
        
        // Ignore player balance and set price basically to 0
        event.setEventResult(Result.FORCE);
    }

    @Subscribe
    public void onPlayerBoughtPlot(PostPlayerBuyPlotEvent event) {
        event.getPlotPlayer().sendMessage(StaticCaption.of("Have fun with your plot by " + event.previousOwner().getName() + " " +
                "for which you paid " + event.price()));
    }
```

```[tasklist]
### Submitter Checklist
- [x] Make sure you are opening from a topic branch (**/feature/fix/docs/ branch** (right side)) and not your main branch.
- [x] Ensure that the pull request title represents the desired changelog entry.
- [x] New public fields and methods are annotated with `@since TODO`.
- [x] I read and followed the [contribution guidelines](https://github.com/IntellectualSites/.github/blob/main/CONTRIBUTING.md).
```

### CODE REVIEW

**Review by NotMyFault — APPROVED** [review]

**Comment by NotMyFault** [comment]
Optionally, would you mind adding todo annotations to the interface methods added?

**Comment by PierreSchwang** [comment]
> Optionally, would you mind adding todo annotations to the interface methods added?

The interface itself shouldn't have any method changes, just the one deprecation and annotations

**Comment by NotMyFault** [comment]
Do you want to file the HoloPlots PR? @PierreSchwang

**Comment by PierreSchwang** [comment]
> Do you want to file the HoloPlots PR? @PierreSchwang

Possibly adding that to the existing PR if not merged until then. But that's the plan, yeah

**Pull request merged**
