### PR TITLE
Prevent dragon eggs from leaving or entering plot bounds

### PR DESCRIPTION
**Pull request by ThisIsIPat**
Dragon eggs can be teleported onto the road if interacted with. Read [this issue](https://github.com/IntellectualSites/PlotSquared/issues/3074) for more details.

The event handler now explicitly handles Dragon Eggs.

I have also been happy to fix a typo in a debug message within the event handler. :)

**Fixes https://github.com/IntellectualSites/PlotSquared/issues/3074**

### CODE REVIEW

**Comment by ThisIsIPat** [comment]
This will remain a draft until it can be tested properly

**Comment by ThisIsIPat** [comment]
Update: Via logging, the cancellation statement in the BlockFromToEvent was found to be reached, but setting it to true doesn't actually cancel the teleportation. Code mostly appears to be correct.

**Comment by ThisIsIPat** [comment]
The cancellation bug was a local testing environment issue. The feature appears to be working as intended.

**Comment by ThisIsIPat** [comment]
**Fixes https://github.com/IntellectualSites/PlotSquared/issues/3076**

**Review by NotMyFault — APPROVED** [review]
Good catch!

**Review by SirYwell — APPROVED** [review]

**Pull request merged**
