### PR TITLE
PlotSquared is no longer on maven

### PR DESCRIPTION
**Pull request by manuelgu**

### CODE REVIEW

**Comment by 20zinnm** [comment]
@manuelgu I would be glad to host a maven repo with it if hosting was the issue.

**Comment by RoboMWM** [comment]
Would definitely like to see PS^2 remain on maven.

**Comment by manuelgu** [comment]
One could also host the Maven Repository in a new branch on a GitHub Repository. @boy0001, thoughts?

**Comment by 20zinnm** [comment]
http://stackoverflow.com/questions/14013644/hosting-a-maven-repository-on-github <http://stackoverflow.com/questions/14013644/hosting-a-maven-repository-on-github>

I just added PlotSquared to my local repo, but this would make it so much better.

**Comment by sgdc3** [comment]
A jenkins instance would be better. I've added it to the AuthMe jenkins repo: 
Jenkins: http://ci.xephi.fr/job/PlotSquared/ 
Mvn Repo: http://ci.xephi.fr/plugin/repository/everything/

**Comment by Sauilitired** [comment]
@sgdc3 If this is a stable server, then would you mind me updating the readme to contain this information?

**Comment by Sauilitired** [comment]
Related compilation error:
`[ERROR] Failed to execute goal on project PlotSquared: Could not resolve dependencies for project com.intellectualcrafters:PlotSquared:jar:3.2.24: Could not find artifact me.confuser:BarAPI:jar:2.0 in techcable-repo (http://repo.techcable.net/content/groups/public/) -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
`

**Pull request closed without merging**
