### PR TITLE
Fix for unwanted audio panning

### LINKED ISSUE #3422: Plot Music should not be a pain with stereo audio
### What feature do you want to see added?

Plot music is placed at the point where the player enters the plot.
This makes it so that with headphones, one side can be louder than the other (total loudness stays the same).
[relevant line of code](https://github.com/IntellectualSites/PlotSquared/blob/47ae79e1231dcbe12be354759d7ca02f36bfae0d/Core/src/main/java/com/plotsquared/core/listener/PlotListener.java#L281)

Now, this can actually be fixed by placing the sound source far above the player (at the center of the plot).
What I did notice is that bukkit is weirdly missing the `minimumVolume` argument for playSound. But im sure there is a distance where it doesnt go quiter. Maybe someone can go whine to the bukkit people.

### Are there any alternatives?

No

### Anything else?

https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/entity/Player.html#playSound(org.bukkit.Location,java.lang.String,float,float)
^ source for my claims about bukkit

### PR DESCRIPTION
**Pull request by StealWonders**
## Overview
Fixes #3422

## Description
This pull request fixes audio (plot music) being played on one ear.

## Submitter Checklist
- [X] Make sure you are opening from a topic branch (**/feature/fix/docs/ branch** (right side)) and not your main branch.
- [X] Ensure that the pull request title represents the desired changelog entry.
- [X] I tested my changes and approved their functionality.
- [ ] I ensured my changes do not break other parts of the code
- [X] I read and followed the [contribution guidelines](https://github.com/IntellectualSites/.github/blob/main/CONTRIBUTING.md)

## Maintainer checklist

Before the changes are marked as `Ready for merge`: 

- [x] There are at least 2 approvals from project developers or maintainers for the pull request and no outstanding requests for change
- [x] Conversations in the pull request are over OR it is explicit that a reviewer does not block the change
- [x] Changelog entries in the PR title are correct
- [x] Proper changelog labels are set so that the changelog can be generated automatically
- [ ] If the change needs additional modification steps from users, e.g. for permission changes, make sure the entry is added to the pull request description so it can be appended to the changelog.

### CODE REVIEW

**Comment by StealWonders** [comment]
Some open questions still remain: when is this condition ever met? https://github.com/IntellectualSites/PlotSquared/blob/9cae938ea4ad42acb94b020133297229762beb3f/Core/src/main/java/com/plotsquared/core/listener/PlotListener.java#L283 And for what reason is the location saved?

**Comment by NotMyFault** [comment]
> Some open questions still remain: when is this condition ever met?
> 
> https://github.com/IntellectualSites/PlotSquared/blob/9cae938ea4ad42acb94b020133297229762beb3f/Core/src/main/java/com/plotsquared/core/listener/PlotListener.java#L283
> 
> And for what reason is the location saved?
> I have tried various ways to try to trigger the condition but I never actually got it to be non-null. Is there an example test-case someone could provide?

A possible condition would be teleporting from another non plot world directly onto the plot, the music would then play twice.

**Comment by StealWonders** [comment]
> > Some open questions still remain: when is this condition ever met?
> > https://github.com/IntellectualSites/PlotSquared/blob/9cae938ea4ad42acb94b020133297229762beb3f/Core/src/main/java/com/plotsquared/core/listener/PlotListener.java#L283
> > 
> > And for what reason is the location saved?
> > I have tried various ways to try to trigger the condition but I never actually got it to be non-null. Is there an example test-case someone could provide?
> 
> A possible condition would be teleporting from another non plot world directly onto the plot, the music would then play twice.

I tried this and it doesn't seem to trigger it.
I'm in a non-plot world and execute `/execute in minecraft:<plotworld> run teleport StealWonders <plot coordinates>`

**Comment by NotMyFault** [comment]
`/plot home` while setting the home location on a plot delivers sufficient results.

**Comment by StealWonders** [comment]
> `/plot home` while setting the home location on a plot delivers sufficient results.

This does not yield the same result on my side... am I doing something wrong?

**Comment by NotMyFault** [comment]
Works as described on my iMac and Macbook.

**Comment by NotMyFault** [comment]
Amendment: I'm not able to reproduce it on a factory standard Surface, this may be some configuration shenanigans I have no time to investigate into.

**Review by Citymonstret — APPROVED** [review]

**Comment by StealWonders** [comment]
@NotMyFault I have been unable to figure out how to trigger the `if (lastLocation != null) {` branch. Would you be able to test the changes for me? If all is well I shall remove the commented-out code.

**Comment by StealWonders** [comment]
I have also noticed when you are on a plot and then use `/plot music` to change the music the plot entry titles and probably other code from the `public boolean plotEntry(final PlotPlayer<?> player, final Plot plot)` method is run. Is this a bug?

**Comment by NotMyFault** [comment]
> @NotMyFault I have been unable to figure out how to trigger the `if (lastLocation != null) {` branch. Would you be able to test the changes for me? If all is well I shall remove the commented-out code.

Changes look good, I don't know when this condition is met.

> I have also noticed when you are on a plot and then use `/plot music` to change the music the plot entry titles and probably other code from the `public boolean plotEntry(final PlotPlayer<?> player, final Plot plot)` method is run. Is this a bug?

Afaik that is used to refresh the player meta, similar procedure is done for the title flag.

**Comment by StealWonders** [comment]
> Afaik that is used to refresh the player meta, similar procedure is done for the title flag.

Yeah, this happens when you update a flag and `plot.reEnter()` is called.  This means that cosmetic things like titles being displayed will happen noticeably even if the title didn't update (if that even is a feature). I guess this is a non-issue?

**Comment by NotMyFault** [comment]
Yes, that's how it always worked.

**Review by NotMyFault — APPROVED** [review]
Looks good, thanks for your contribution!

This PR is ready to be merged, we will merge it in ~24 hours if there is no negative feedback, as documented by the [merge process](https://github.com/IntellectualSites/IntellectualSites/blob/main/docs/MAINTAINERS_CONTRIBUTORS.adoc#merge-process) documentation.

**Pull request merged**
