### PR TITLE
Push target folder as it is needed for /p update

### PR DESCRIPTION
**Pull request by manuelgu**

### CODE REVIEW

**Comment by manuelgu** [comment]
If anybody would like to build and push the newest version so we can fix /p update again? :)

**Comment by Sauilitired** [comment]
@manuelgu I can do it in a couple of hours, unless someone does it before me :)

**Comment by manuelgu** [comment]
@Sauilitired :)

**Comment by Sauilitired** [comment]
@manuelgu a couple of hours can also mean a week.

**Comment by manuelgu** [comment]
@Sauilitired also 2 1/2 weeks?

**Comment by Sauilitired** [comment]
@manuelgu Of course; though, this shouldn't be used as the major bugs are still present. Would be stupid to update to another broken version.

**Pull request merged**
