### PR TITLE
Don't expose jcip and findbugs annotations to the world on runtime

### PR DESCRIPTION
**Pull request by NotMyFault**
## Description
The change proposed addresses findbugs and jcip not being relocated in the jar.
Additionally labeling as "Developer", because you never know where people pull their dependencies from...
I've also taken the shot to reorganize our internal structure of dependencies, grouping them in sub folders.

## Submitter Checklist

- [X] Make sure you are opening from a topic branch (**/feature/fix/docs/ branch** (right side)) and not your main branch.
- [X] Ensure that the pull request title represents the desired changelog entry.
- [X] I tested my changes and approved their functionality.
- [X] I ensured my changes do not break other parts of the code
- [X] I read and followed the [contribution guidelines](https://github.com/IntellectualSites/.github/blob/main/CONTRIBUTING.md)

### CODE REVIEW

**Comment by dordsor21** [comment]
Is it worth grouping and commenting by the subpackage (web/internal etc)?

**Review by dordsor21 — APPROVED** [review]
¯\_(ツ)_/¯

**Comment by SirYwell** [comment]
Modifying relocations of libraries exposed in API is a breaking change. Especially guice should be considered here I think.

**Comment by NotMyFault** [comment]
> Modifying relocations of libraries exposed in API is a breaking change. Especially guice should be considered here I think.

We don't publish shadow artifacts, none of the relocation is available in the API artifacts in any way.

**Comment by NotMyFault** [comment]
I've reverted the commit to comply with the PR title. I'll look forward to change the relocation pattern within v7, yet to notice, this still doesn't affect API consumers, because we don't publish builds containing these libraries.

cc @SirYwell

**Review by SirYwell — APPROVED** [review]

**Pull request merged**
