### PR TITLE
Drop informational guava and JB annotations

### PR DESCRIPTION
**Pull request by NotMyFault**
## Description
I dropped the beta annotation from the comment manager, considering it _should_ have matured well over the years we have had it there. 
Additionally, I dropped JB's `ApiStatus` annotations, because we're using Checkerframework for everything.
However, unless I missed informational classes, checker(qual) does not have any sort of these kinds, so I created an internal `AnnotationHelper`, that can be used to provide additional information about how to, or how not to, use parts of the API.
Maybe we're going to add more custom annotations in the future.
To note, AnnotationHelper#ApiDescription allows you to define an info string and does not display plain `@Internal` how JB used to.

## Submitter Checklist

- [X] Make sure you are opening from a topic branch (**/feature/fix/docs/ branch** (right side)) and not your main branch.
- [X] Ensure that the pull request title represents the desired changelog entry.
- [X] I tested my changes and approved their functionality.
- [X] I ensured my changes do not break other parts of the code
- [X] I read and followed the [contribution guidelines](https://github.com/IntellectualSites/.github/blob/main/CONTRIBUTING.md)

## Maintainer checklist

Before the changes are marked as `Ready for merge`: 

- [ ] There are at least 2 approvals for the pull request and no outstanding requests for change
- [ ] Conversations in the pull request are over OR it is explicit that a reviewer does not block the change
- [X] Changelog entries in the PR title are correct
- [X] Proper changelog labels are set so that the changelog can be generated automatically
- [ ] If the change needs additional modification steps from users, e.g. for permission changes, make sure the entry is added to the pull request description so it can be appended to the changelog.

### CODE REVIEW

**Review by SirYwell — APPROVED** [review]
Looks fine, but is the AnnotationHelper actually needed?

**Comment by NotMyFault** [comment]
> Looks fine, but is the AnnotationHelper actually needed?

Maybe it's some sort of preference, but annotations are displayed above comments in javadocs, which may be better for visibility, especially for something you may not use.

**Comment by NotMyFault** [comment]
@dordsor21 you able to take a look?

**Review by dordsor21 — APPROVED** [review]
We should have a follow-up PR adding this where needed I think

**Comment by NotMyFault** [comment]
We may merge it in 24 hours if there is no negative feedback, as per the [merge process ](https://github.com/IntellectualSites/IntellectualSites/blob/main/docs/MAINTAINERS_CONTRIBUTORS.adoc#merge-process) documentation.

cc dords, that may be something for a follow up, maybe I can head towards it later this week.

**Comment by dordsor21** [comment]
> We may merge it in 24 hours if there is no negative feedback, as per the [merge process ](https://github.com/IntellectualSites/IntellectualSites/blob/main/docs/MAINTAINERS_CONTRIBUTORS.adoc?rgh-link-date=2021-12-28T15%3A47%3A11Z#merge-process) documentation.
> 
> cc dords, that may be something for a follow up, maybe I can head towards it later this week.

Sounds good. Might be worth having something similar in FAWE too

**Comment by NotMyFault** [comment]
> > We may merge it in 24 hours if there is no negative feedback, as per the [merge process ](https://github.com/IntellectualSites/IntellectualSites/blob/main/docs/MAINTAINERS_CONTRIBUTORS.adoc?rgh-link-date=2021-12-28T15%3A47%3A11Z#merge-process) documentation.
> > cc dords, that may be something for a follow up, maybe I can head towards it later this week.
> 
> Sounds good. Might be worth having something similar in FAWE too

WorldEdit has a proposal to switch to JB annotations overall instead of JSR. JB has something like ApiStatus#Internal, #Eperimental and so on we could utilize then.

**Pull request merged**
