### PR TITLE
New plot flag untrusted-visit

### PR DESCRIPTION
**Pull request by mindw0rm**
## Overview

This adds a new flag 'untrusted-visit' which allows plot owners to make their plot(s) reachable to everyone via the visit command. 

**Fixes IntellectualSites/PlotSquaredSuggestions#64**

## Description
Besides adding the new flag itself, it is checked in two locations:
* in the Visit command: to allow visiting if the player is not trusted and doesn't have the permission `plots.visit.other` (i.e. main functionality of the flag)
* in the onTeleport event, where `deny-teleport` is checked.
  The reasoning here is that you'll want `untrusted-visit` to override `deny-teleport`, or else it won't make sense to set both flags. With this change you can prevent players to teleport within your plot (at least with my bugfix #2506 or equivalent changes), but still allow visits (denying teleports is mandatory for things like e.g. labyrinths or jump'n'run courses (else cheating would be possible with ender pearls or chorus fruits), but if they can't use visit, they'll have to walk to the plot). 
Note that this is only implemented for bukkit (because deny-teleport is only checked for bukkit as well, and also because I can't test the others ;) ).

The last change is adding a new method getLocationFull to BukkitUtil, which transforms a bukkit Location into a PlotSquared Location _including_ yaw and pitch, since this is required for the location compare, and adding the copying of yaw and pitch to one of the existing ``getLocation` methods gave me a bad feeling regarding side effects. 

So the flag is considered only under very specific conditions, so it shouldn't have any side effects to other functionality. 

## Checklist

- [X] I included all information required in the sections above
- [X] I tested my changes and approved their functionality
- [X] I ensured my changes do not break other parts of the code
- [X] I read and followed the [contribution guidelines](https://github.com/IntellectualSites/PlotSquared/blob/breaking/CONTRIBUTING.md)

### CODE REVIEW

**Comment by mindw0rm** [comment]
Obviously you don't want this. Sorry that I bothered you.

**Comment by Sauilitired** [comment]
It makes everything slightly more complex, but considering the feature is opt-in and won't affect any existing setups, I don't have any objections.

@mindw0rm Thanks for contributing to PlotSquared, I sincerely mean that. I'm sorry that the conversation in the issue report took a sour turn.

**Comment by MattBDev** [comment]
@mindw0rm can you please resolve the merge conflicts?

**Comment by mindw0rm** [comment]
@MattBDev done

**Pull request merged**
